// <auto-generated />
using System;
using CheckInSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CheckInSystem.Data.Migrations
{
    [DbContext(typeof(CheckInDbContext))]
    [Migration("20250521110021_InitWithFullSeed")]
    partial class InitWithFullSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("CheckInSystem.Data.Models.Flight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DepartureTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("FlightNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Flights");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartureTime = new DateTime(2025, 5, 15, 8, 0, 0, 0, DateTimeKind.Utc),
                            FlightNumber = "US123",
                            Status = "Scheduled"
                        },
                        new
                        {
                            Id = 2,
                            DepartureTime = new DateTime(2025, 5, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            FlightNumber = "CN234",
                            Status = "Scheduled"
                        },
                        new
                        {
                            Id = 3,
                            DepartureTime = new DateTime(2025, 5, 15, 10, 0, 0, 0, DateTimeKind.Utc),
                            FlightNumber = "FR345",
                            Status = "Scheduled"
                        },
                        new
                        {
                            Id = 4,
                            DepartureTime = new DateTime(2025, 5, 15, 11, 0, 0, 0, DateTimeKind.Utc),
                            FlightNumber = "JP456",
                            Status = "Scheduled"
                        },
                        new
                        {
                            Id = 5,
                            DepartureTime = new DateTime(2025, 5, 15, 12, 0, 0, 0, DateTimeKind.Utc),
                            FlightNumber = "DE567",
                            Status = "Scheduled"
                        },
                        new
                        {
                            Id = 6,
                            DepartureTime = new DateTime(2025, 5, 15, 13, 0, 0, 0, DateTimeKind.Utc),
                            FlightNumber = "MN678",
                            Status = "Scheduled"
                        });
                });

            modelBuilder.Entity("CheckInSystem.Data.Models.Passenger", b =>
                {
                    b.Property<int>("PassengerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FlightId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PassportNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("PassengerId");

                    b.ToTable("Passengers");

                    b.HasData(
                        new
                        {
                            PassengerId = 1,
                            FlightId = 1,
                            FullName = "Alice Johnson",
                            PassportNumber = "AA1234567",
                            Status = 0
                        },
                        new
                        {
                            PassengerId = 2,
                            FlightId = 1,
                            FullName = "Bob Smith",
                            PassportNumber = "BB2345678",
                            Status = 0
                        },
                        new
                        {
                            PassengerId = 3,
                            FlightId = 1,
                            FullName = "Charlie Lee",
                            PassportNumber = "CC3456789",
                            Status = 0
                        },
                        new
                        {
                            PassengerId = 4,
                            FlightId = 1,
                            FullName = "Diana King",
                            PassportNumber = "DD4567890",
                            Status = 0
                        },
                        new
                        {
                            PassengerId = 5,
                            FlightId = 1,
                            FullName = "Ethan Hall",
                            PassportNumber = "EE5678901",
                            Status = 0
                        },
                        new
                        {
                            PassengerId = 6,
                            FlightId = 2,
                            FullName = "Fiona White",
                            PassportNumber = "FF6789012",
                            Status = 0
                        },
                        new
                        {
                            PassengerId = 7,
                            FlightId = 2,
                            FullName = "George Brown",
                            PassportNumber = "GG7890123",
                            Status = 0
                        },
                        new
                        {
                            PassengerId = 8,
                            FlightId = 2,
                            FullName = "Hannah Scott",
                            PassportNumber = "HH8901234",
                            Status = 0
                        },
                        new
                        {
                            PassengerId = 9,
                            FlightId = 2,
                            FullName = "Ian Davis",
                            PassportNumber = "II9012345",
                            Status = 0
                        },
                        new
                        {
                            PassengerId = 10,
                            FlightId = 2,
                            FullName = "Jane Miller",
                            PassportNumber = "JJ0123456",
                            Status = 0
                        },
                        new
                        {
                            PassengerId = 11,
                            FlightId = 3,
                            FullName = "Kevin Wilson",
                            PassportNumber = "KK1234567",
                            Status = 0
                        },
                        new
                        {
                            PassengerId = 12,
                            FlightId = 3,
                            FullName = "Luna Thomas",
                            PassportNumber = "LL2345678",
                            Status = 0
                        },
                        new
                        {
                            PassengerId = 13,
                            FlightId = 3,
                            FullName = "Michael Lewis",
                            PassportNumber = "MM3456789",
                            Status = 0
                        },
                        new
                        {
                            PassengerId = 14,
                            FlightId = 3,
                            FullName = "Nora Harris",
                            PassportNumber = "NN4567890",
                            Status = 0
                        },
                        new
                        {
                            PassengerId = 15,
                            FlightId = 3,
                            FullName = "Oliver Young",
                            PassportNumber = "OO5678901",
                            Status = 0
                        },
                        new
                        {
                            PassengerId = 16,
                            FlightId = 4,
                            FullName = "Paula Green",
                            PassportNumber = "PP6789012",
                            Status = 0
                        },
                        new
                        {
                            PassengerId = 17,
                            FlightId = 4,
                            FullName = "Quentin Hill",
                            PassportNumber = "QQ7890123",
                            Status = 0
                        },
                        new
                        {
                            PassengerId = 18,
                            FlightId = 4,
                            FullName = "Rachel Adams",
                            PassportNumber = "RR8901234",
                            Status = 0
                        },
                        new
                        {
                            PassengerId = 19,
                            FlightId = 4,
                            FullName = "Samuel Baker",
                            PassportNumber = "SS9012345",
                            Status = 0
                        },
                        new
                        {
                            PassengerId = 20,
                            FlightId = 4,
                            FullName = "Tina Clark",
                            PassportNumber = "TT0123456",
                            Status = 0
                        },
                        new
                        {
                            PassengerId = 21,
                            FlightId = 5,
                            FullName = "Umar Turner",
                            PassportNumber = "UU1234567",
                            Status = 0
                        },
                        new
                        {
                            PassengerId = 22,
                            FlightId = 5,
                            FullName = "Violet Moore",
                            PassportNumber = "VV2345678",
                            Status = 0
                        },
                        new
                        {
                            PassengerId = 23,
                            FlightId = 5,
                            FullName = "William Wright",
                            PassportNumber = "WW3456789",
                            Status = 0
                        },
                        new
                        {
                            PassengerId = 24,
                            FlightId = 5,
                            FullName = "Xenia Lopez",
                            PassportNumber = "XX4567890",
                            Status = 0
                        },
                        new
                        {
                            PassengerId = 25,
                            FlightId = 5,
                            FullName = "Yusuf Walker",
                            PassportNumber = "YY5678901",
                            Status = 0
                        },
                        new
                        {
                            PassengerId = 26,
                            FlightId = 6,
                            FullName = "Zara Price",
                            PassportNumber = "ZZ6789012",
                            Status = 0
                        },
                        new
                        {
                            PassengerId = 27,
                            FlightId = 6,
                            FullName = "Aaron Murphy",
                            PassportNumber = "AB7890123",
                            Status = 0
                        },
                        new
                        {
                            PassengerId = 28,
                            FlightId = 6,
                            FullName = "Beatrice Wood",
                            PassportNumber = "CD8901234",
                            Status = 0
                        },
                        new
                        {
                            PassengerId = 29,
                            FlightId = 6,
                            FullName = "Caleb Reed",
                            PassportNumber = "EF9012345",
                            Status = 0
                        },
                        new
                        {
                            PassengerId = 30,
                            FlightId = 6,
                            FullName = "Dana Collins",
                            PassportNumber = "GH0123456",
                            Status = 0
                        });
                });

            modelBuilder.Entity("CheckInSystem.Data.Models.Seat", b =>
                {
                    b.Property<int>("SeatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FlightId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsOccupied")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PassengerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SeatNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("SeatId");

                    b.HasIndex("FlightId");

                    b.HasIndex("PassengerId");

                    b.ToTable("Seats");

                    b.HasData(
                        new
                        {
                            SeatId = 1,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "S01"
                        },
                        new
                        {
                            SeatId = 2,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "S02"
                        },
                        new
                        {
                            SeatId = 3,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "S03"
                        },
                        new
                        {
                            SeatId = 4,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "S04"
                        },
                        new
                        {
                            SeatId = 5,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "S05"
                        },
                        new
                        {
                            SeatId = 6,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "S06"
                        },
                        new
                        {
                            SeatId = 7,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "S07"
                        },
                        new
                        {
                            SeatId = 8,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "S08"
                        },
                        new
                        {
                            SeatId = 9,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "S09"
                        },
                        new
                        {
                            SeatId = 10,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "S10"
                        },
                        new
                        {
                            SeatId = 11,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "S11"
                        },
                        new
                        {
                            SeatId = 12,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "S12"
                        },
                        new
                        {
                            SeatId = 13,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "S13"
                        },
                        new
                        {
                            SeatId = 14,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "S14"
                        },
                        new
                        {
                            SeatId = 15,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "S15"
                        },
                        new
                        {
                            SeatId = 16,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "S16"
                        },
                        new
                        {
                            SeatId = 17,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "S17"
                        },
                        new
                        {
                            SeatId = 18,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "S18"
                        },
                        new
                        {
                            SeatId = 19,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "S19"
                        },
                        new
                        {
                            SeatId = 20,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "S20"
                        },
                        new
                        {
                            SeatId = 21,
                            FlightId = 2,
                            IsOccupied = false,
                            SeatNumber = "S01"
                        },
                        new
                        {
                            SeatId = 22,
                            FlightId = 2,
                            IsOccupied = false,
                            SeatNumber = "S02"
                        },
                        new
                        {
                            SeatId = 23,
                            FlightId = 2,
                            IsOccupied = false,
                            SeatNumber = "S03"
                        },
                        new
                        {
                            SeatId = 24,
                            FlightId = 2,
                            IsOccupied = false,
                            SeatNumber = "S04"
                        },
                        new
                        {
                            SeatId = 25,
                            FlightId = 2,
                            IsOccupied = false,
                            SeatNumber = "S05"
                        },
                        new
                        {
                            SeatId = 26,
                            FlightId = 2,
                            IsOccupied = false,
                            SeatNumber = "S06"
                        },
                        new
                        {
                            SeatId = 27,
                            FlightId = 2,
                            IsOccupied = false,
                            SeatNumber = "S07"
                        },
                        new
                        {
                            SeatId = 28,
                            FlightId = 2,
                            IsOccupied = false,
                            SeatNumber = "S08"
                        },
                        new
                        {
                            SeatId = 29,
                            FlightId = 2,
                            IsOccupied = false,
                            SeatNumber = "S09"
                        },
                        new
                        {
                            SeatId = 30,
                            FlightId = 2,
                            IsOccupied = false,
                            SeatNumber = "S10"
                        },
                        new
                        {
                            SeatId = 31,
                            FlightId = 2,
                            IsOccupied = false,
                            SeatNumber = "S11"
                        },
                        new
                        {
                            SeatId = 32,
                            FlightId = 2,
                            IsOccupied = false,
                            SeatNumber = "S12"
                        },
                        new
                        {
                            SeatId = 33,
                            FlightId = 2,
                            IsOccupied = false,
                            SeatNumber = "S13"
                        },
                        new
                        {
                            SeatId = 34,
                            FlightId = 2,
                            IsOccupied = false,
                            SeatNumber = "S14"
                        },
                        new
                        {
                            SeatId = 35,
                            FlightId = 2,
                            IsOccupied = false,
                            SeatNumber = "S15"
                        },
                        new
                        {
                            SeatId = 36,
                            FlightId = 2,
                            IsOccupied = false,
                            SeatNumber = "S16"
                        },
                        new
                        {
                            SeatId = 37,
                            FlightId = 2,
                            IsOccupied = false,
                            SeatNumber = "S17"
                        },
                        new
                        {
                            SeatId = 38,
                            FlightId = 2,
                            IsOccupied = false,
                            SeatNumber = "S18"
                        },
                        new
                        {
                            SeatId = 39,
                            FlightId = 2,
                            IsOccupied = false,
                            SeatNumber = "S19"
                        },
                        new
                        {
                            SeatId = 40,
                            FlightId = 2,
                            IsOccupied = false,
                            SeatNumber = "S20"
                        },
                        new
                        {
                            SeatId = 41,
                            FlightId = 3,
                            IsOccupied = false,
                            SeatNumber = "S01"
                        },
                        new
                        {
                            SeatId = 42,
                            FlightId = 3,
                            IsOccupied = false,
                            SeatNumber = "S02"
                        },
                        new
                        {
                            SeatId = 43,
                            FlightId = 3,
                            IsOccupied = false,
                            SeatNumber = "S03"
                        },
                        new
                        {
                            SeatId = 44,
                            FlightId = 3,
                            IsOccupied = false,
                            SeatNumber = "S04"
                        },
                        new
                        {
                            SeatId = 45,
                            FlightId = 3,
                            IsOccupied = false,
                            SeatNumber = "S05"
                        },
                        new
                        {
                            SeatId = 46,
                            FlightId = 3,
                            IsOccupied = false,
                            SeatNumber = "S06"
                        },
                        new
                        {
                            SeatId = 47,
                            FlightId = 3,
                            IsOccupied = false,
                            SeatNumber = "S07"
                        },
                        new
                        {
                            SeatId = 48,
                            FlightId = 3,
                            IsOccupied = false,
                            SeatNumber = "S08"
                        },
                        new
                        {
                            SeatId = 49,
                            FlightId = 3,
                            IsOccupied = false,
                            SeatNumber = "S09"
                        },
                        new
                        {
                            SeatId = 50,
                            FlightId = 3,
                            IsOccupied = false,
                            SeatNumber = "S10"
                        },
                        new
                        {
                            SeatId = 51,
                            FlightId = 3,
                            IsOccupied = false,
                            SeatNumber = "S11"
                        },
                        new
                        {
                            SeatId = 52,
                            FlightId = 3,
                            IsOccupied = false,
                            SeatNumber = "S12"
                        },
                        new
                        {
                            SeatId = 53,
                            FlightId = 3,
                            IsOccupied = false,
                            SeatNumber = "S13"
                        },
                        new
                        {
                            SeatId = 54,
                            FlightId = 3,
                            IsOccupied = false,
                            SeatNumber = "S14"
                        },
                        new
                        {
                            SeatId = 55,
                            FlightId = 3,
                            IsOccupied = false,
                            SeatNumber = "S15"
                        },
                        new
                        {
                            SeatId = 56,
                            FlightId = 3,
                            IsOccupied = false,
                            SeatNumber = "S16"
                        },
                        new
                        {
                            SeatId = 57,
                            FlightId = 3,
                            IsOccupied = false,
                            SeatNumber = "S17"
                        },
                        new
                        {
                            SeatId = 58,
                            FlightId = 3,
                            IsOccupied = false,
                            SeatNumber = "S18"
                        },
                        new
                        {
                            SeatId = 59,
                            FlightId = 3,
                            IsOccupied = false,
                            SeatNumber = "S19"
                        },
                        new
                        {
                            SeatId = 60,
                            FlightId = 3,
                            IsOccupied = false,
                            SeatNumber = "S20"
                        },
                        new
                        {
                            SeatId = 61,
                            FlightId = 4,
                            IsOccupied = false,
                            SeatNumber = "S01"
                        },
                        new
                        {
                            SeatId = 62,
                            FlightId = 4,
                            IsOccupied = false,
                            SeatNumber = "S02"
                        },
                        new
                        {
                            SeatId = 63,
                            FlightId = 4,
                            IsOccupied = false,
                            SeatNumber = "S03"
                        },
                        new
                        {
                            SeatId = 64,
                            FlightId = 4,
                            IsOccupied = false,
                            SeatNumber = "S04"
                        },
                        new
                        {
                            SeatId = 65,
                            FlightId = 4,
                            IsOccupied = false,
                            SeatNumber = "S05"
                        },
                        new
                        {
                            SeatId = 66,
                            FlightId = 4,
                            IsOccupied = false,
                            SeatNumber = "S06"
                        },
                        new
                        {
                            SeatId = 67,
                            FlightId = 4,
                            IsOccupied = false,
                            SeatNumber = "S07"
                        },
                        new
                        {
                            SeatId = 68,
                            FlightId = 4,
                            IsOccupied = false,
                            SeatNumber = "S08"
                        },
                        new
                        {
                            SeatId = 69,
                            FlightId = 4,
                            IsOccupied = false,
                            SeatNumber = "S09"
                        },
                        new
                        {
                            SeatId = 70,
                            FlightId = 4,
                            IsOccupied = false,
                            SeatNumber = "S10"
                        },
                        new
                        {
                            SeatId = 71,
                            FlightId = 4,
                            IsOccupied = false,
                            SeatNumber = "S11"
                        },
                        new
                        {
                            SeatId = 72,
                            FlightId = 4,
                            IsOccupied = false,
                            SeatNumber = "S12"
                        },
                        new
                        {
                            SeatId = 73,
                            FlightId = 4,
                            IsOccupied = false,
                            SeatNumber = "S13"
                        },
                        new
                        {
                            SeatId = 74,
                            FlightId = 4,
                            IsOccupied = false,
                            SeatNumber = "S14"
                        },
                        new
                        {
                            SeatId = 75,
                            FlightId = 4,
                            IsOccupied = false,
                            SeatNumber = "S15"
                        },
                        new
                        {
                            SeatId = 76,
                            FlightId = 4,
                            IsOccupied = false,
                            SeatNumber = "S16"
                        },
                        new
                        {
                            SeatId = 77,
                            FlightId = 4,
                            IsOccupied = false,
                            SeatNumber = "S17"
                        },
                        new
                        {
                            SeatId = 78,
                            FlightId = 4,
                            IsOccupied = false,
                            SeatNumber = "S18"
                        },
                        new
                        {
                            SeatId = 79,
                            FlightId = 4,
                            IsOccupied = false,
                            SeatNumber = "S19"
                        },
                        new
                        {
                            SeatId = 80,
                            FlightId = 4,
                            IsOccupied = false,
                            SeatNumber = "S20"
                        },
                        new
                        {
                            SeatId = 81,
                            FlightId = 5,
                            IsOccupied = false,
                            SeatNumber = "S01"
                        },
                        new
                        {
                            SeatId = 82,
                            FlightId = 5,
                            IsOccupied = false,
                            SeatNumber = "S02"
                        },
                        new
                        {
                            SeatId = 83,
                            FlightId = 5,
                            IsOccupied = false,
                            SeatNumber = "S03"
                        },
                        new
                        {
                            SeatId = 84,
                            FlightId = 5,
                            IsOccupied = false,
                            SeatNumber = "S04"
                        },
                        new
                        {
                            SeatId = 85,
                            FlightId = 5,
                            IsOccupied = false,
                            SeatNumber = "S05"
                        },
                        new
                        {
                            SeatId = 86,
                            FlightId = 5,
                            IsOccupied = false,
                            SeatNumber = "S06"
                        },
                        new
                        {
                            SeatId = 87,
                            FlightId = 5,
                            IsOccupied = false,
                            SeatNumber = "S07"
                        },
                        new
                        {
                            SeatId = 88,
                            FlightId = 5,
                            IsOccupied = false,
                            SeatNumber = "S08"
                        },
                        new
                        {
                            SeatId = 89,
                            FlightId = 5,
                            IsOccupied = false,
                            SeatNumber = "S09"
                        },
                        new
                        {
                            SeatId = 90,
                            FlightId = 5,
                            IsOccupied = false,
                            SeatNumber = "S10"
                        },
                        new
                        {
                            SeatId = 91,
                            FlightId = 5,
                            IsOccupied = false,
                            SeatNumber = "S11"
                        },
                        new
                        {
                            SeatId = 92,
                            FlightId = 5,
                            IsOccupied = false,
                            SeatNumber = "S12"
                        },
                        new
                        {
                            SeatId = 93,
                            FlightId = 5,
                            IsOccupied = false,
                            SeatNumber = "S13"
                        },
                        new
                        {
                            SeatId = 94,
                            FlightId = 5,
                            IsOccupied = false,
                            SeatNumber = "S14"
                        },
                        new
                        {
                            SeatId = 95,
                            FlightId = 5,
                            IsOccupied = false,
                            SeatNumber = "S15"
                        },
                        new
                        {
                            SeatId = 96,
                            FlightId = 5,
                            IsOccupied = false,
                            SeatNumber = "S16"
                        },
                        new
                        {
                            SeatId = 97,
                            FlightId = 5,
                            IsOccupied = false,
                            SeatNumber = "S17"
                        },
                        new
                        {
                            SeatId = 98,
                            FlightId = 5,
                            IsOccupied = false,
                            SeatNumber = "S18"
                        },
                        new
                        {
                            SeatId = 99,
                            FlightId = 5,
                            IsOccupied = false,
                            SeatNumber = "S19"
                        },
                        new
                        {
                            SeatId = 100,
                            FlightId = 5,
                            IsOccupied = false,
                            SeatNumber = "S20"
                        },
                        new
                        {
                            SeatId = 101,
                            FlightId = 6,
                            IsOccupied = false,
                            SeatNumber = "S01"
                        },
                        new
                        {
                            SeatId = 102,
                            FlightId = 6,
                            IsOccupied = false,
                            SeatNumber = "S02"
                        },
                        new
                        {
                            SeatId = 103,
                            FlightId = 6,
                            IsOccupied = false,
                            SeatNumber = "S03"
                        },
                        new
                        {
                            SeatId = 104,
                            FlightId = 6,
                            IsOccupied = false,
                            SeatNumber = "S04"
                        },
                        new
                        {
                            SeatId = 105,
                            FlightId = 6,
                            IsOccupied = false,
                            SeatNumber = "S05"
                        },
                        new
                        {
                            SeatId = 106,
                            FlightId = 6,
                            IsOccupied = false,
                            SeatNumber = "S06"
                        },
                        new
                        {
                            SeatId = 107,
                            FlightId = 6,
                            IsOccupied = false,
                            SeatNumber = "S07"
                        },
                        new
                        {
                            SeatId = 108,
                            FlightId = 6,
                            IsOccupied = false,
                            SeatNumber = "S08"
                        },
                        new
                        {
                            SeatId = 109,
                            FlightId = 6,
                            IsOccupied = false,
                            SeatNumber = "S09"
                        },
                        new
                        {
                            SeatId = 110,
                            FlightId = 6,
                            IsOccupied = false,
                            SeatNumber = "S10"
                        },
                        new
                        {
                            SeatId = 111,
                            FlightId = 6,
                            IsOccupied = false,
                            SeatNumber = "S11"
                        },
                        new
                        {
                            SeatId = 112,
                            FlightId = 6,
                            IsOccupied = false,
                            SeatNumber = "S12"
                        },
                        new
                        {
                            SeatId = 113,
                            FlightId = 6,
                            IsOccupied = false,
                            SeatNumber = "S13"
                        },
                        new
                        {
                            SeatId = 114,
                            FlightId = 6,
                            IsOccupied = false,
                            SeatNumber = "S14"
                        },
                        new
                        {
                            SeatId = 115,
                            FlightId = 6,
                            IsOccupied = false,
                            SeatNumber = "S15"
                        },
                        new
                        {
                            SeatId = 116,
                            FlightId = 6,
                            IsOccupied = false,
                            SeatNumber = "S16"
                        },
                        new
                        {
                            SeatId = 117,
                            FlightId = 6,
                            IsOccupied = false,
                            SeatNumber = "S17"
                        },
                        new
                        {
                            SeatId = 118,
                            FlightId = 6,
                            IsOccupied = false,
                            SeatNumber = "S18"
                        },
                        new
                        {
                            SeatId = 119,
                            FlightId = 6,
                            IsOccupied = false,
                            SeatNumber = "S19"
                        },
                        new
                        {
                            SeatId = 120,
                            FlightId = 6,
                            IsOccupied = false,
                            SeatNumber = "S20"
                        });
                });

            modelBuilder.Entity("CheckInSystem.Data.Models.Seat", b =>
                {
                    b.HasOne("CheckInSystem.Data.Models.Flight", "Flight")
                        .WithMany("Seats")
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CheckInSystem.Data.Models.Passenger", "Passenger")
                        .WithMany()
                        .HasForeignKey("PassengerId");

                    b.Navigation("Flight");

                    b.Navigation("Passenger");
                });

            modelBuilder.Entity("CheckInSystem.Data.Models.Flight", b =>
                {
                    b.Navigation("Seats");
                });
#pragma warning restore 612, 618
        }
    }
}
